- name: Deploy voting app
  hosts: local
  become: yes

  vars:
    repo_url: https://github.com/ayeAlvo/DevOps90Days.git
    project_path: /opt/devops90days
    app_path: "{{ project_path }}/voting-app"

  tasks:

    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install docker compose
      apt:
        name: docker-compose
        state: present

    - name: Clone project repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        update: yes

    - name: Start voting app
      command: docker compose up -d
      args:
        chdir: "{{ app_path }}"

    - name: Show running containers
      command: docker ps