FROM nginx:1.29-alpine
LABEL owner="Aye Onfire" version="1.0" description="Portfolio website showcasing DevOps projects and skills"
ENV PRUEBA="Hola mundo desde Dockerfile"
EXPOSE 80
COPY . /usr/share/nginx/html/
