name: Deploy App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: 3er_semana/deploy-w-github-action/mi-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop containers
        run: docker compose down || true

      - name: Build
        run: docker compose build --no-cache

      - name: Up
        run: docker compose up -d

      - name: Healthcheck
        run: |
          sleep 10
          curl -f http://localhost/health